/* dg_recog.h Recognise file types
**
** Maf - 09.10.96 - Created
**
*/


/*[ Prototypes ]*************************************************************/

int extractnum( char *S, char Len, char Hex );     /* Get number from a string */
int recognise_file( char *path, char *filename );  /* Identify file type       */

/****************************************************************************/

